# 公共环境配置
COMMON: &common  # 标识
  # app设置
  DEBUG: False
  SECRET_KEY: insecure
  TESTING: False
  THREADED: False
  # 页面配置
  DEFAULT_PAGE_INDEX: 1
  DEFAULT_PAGE_SIZE: 10
  # 日志配置
  LOGGING_CONFIG_PATH: ./config/logging.yaml  # 日志配置文件路径
  LOGGING_PATH: ./logs  # 日志文件存放位置
  # 响应消息
  RESPONSE_MESSAGE: ./config/msg.yaml
  # 数据库连接
  SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:123456@localhost:3306/test?charset=utf8mb4'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  SQLALCHEMY_COMMIT_ON_TEARDOWN: False

# 开发环境配置
DEVELOPMENT: &development
  <<: *common  # 继承common,使用其下面的所有配置
  DEBUG: True
  ENV: dev

# 测试环境配置
TESTING: &testing
  <<: *common
  ENV: test
  TESTING: True

# 模拟环境配置,为生产环境的镜像
STAGING: &staging
  <<: *common
  SECRET_KEY: sortsecure

# 生产环境配置
PRODUCTION: &production
  <<: *common
  ENV: prod
  SECRET_KEY: mdd1
